### ISSUE TITLE
crashing when entering combat bar

### ISSUE THREAD

**Issue by BonnieGecko3493** [rathmerdominik/mine-mine-no-mi-modded#2]
Error: java.lang.NoSuchMethodError: xyz.pixelatedw.mineminenomi.api.helpers.HakiHelper.getHaoshokuColour(Lnet/minecraft/entity/LivingEntity;)I
1.16.5. Forge - 36.2.34

**Comment by rathmerdominik** [comment]
This repo is no longer needed 😄 
All changes are now ported in the 0.10.0 version of Mine Mine no Mi!

Please use that.
